from brownie import accounts, config
import os


def deploy_simple_storage():

    # ## 1 in 10 Fake account generated by brownie
    # account = accounts[0]

    # ## Saved accounts
    # account = accounts.load("mm-account1")

    # ## Private key in environment variable
    # account = accounts.add(os.getenv("PRIVATE_KEY1"))

    ## Private key in environment variable via config
    account = accounts.add(config["wallets"]["from_key"])

    print(account)


def main():
    deploy_simple_storage()
