from brownie import accounts, config, SimpleStorage, network
import os


def deploy_simple_storage():

    # ## 1 in 10 Fake account generated by brownie
    # account = accounts[0]

    # ## Saved accounts
    # account = accounts.load("mm-account1")

    # ## Private key in environment variable
    # account = accounts.add(os.getenv("PRIVATE_KEY1"))

    # ## Private key in environment variable via config
    # account = accounts.add(config["wallets"]["from_key"])

    account = get_account()
    print(account)

    ## Deploy to chain
    simple_storage = SimpleStorage.deploy({"from": account})
    print(simple_storage)

    ## Read
    stored_value = simple_storage.retrieve()
    print(stored_value)

    ## Write
    transaction = simple_storage.store(1500, {"from": account})
    transaction.wait(1)
    print(transaction)

    ## Read again
    stored_value = simple_storage.retrieve()
    print(stored_value)


def get_account():
    if network.show_active() == "development":
        return accounts[0]
    else:
        return accounts.add(config["wallets"]["from_key"])


def main():
    deploy_simple_storage()
